services:
  # Static Site service
  - type: web
    name: simplepoordashboard
    env: static
    rootDir: ./
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: 0